version: '3'
services:
  cstrike:
    container_name: cstrike-server
    build: .
    restart: always
    environment:
      PORT: 27015
      MAP: de_dust2
      MAXPLAYERS: 16
      SV_LAN: 0
    ports:
      - "27015:27015/udp"
      - "27015:27015"
    volumes:
      - /opt/cs/server.cfg:/home/steam/cstrike/cstrike/server.cfg
      - /opt/cs/mapcycle.txt:/home/steam/cstrike/cstrike/mapcycle.txt